binaries:
    neofs_cli:
        repo: 'nspcc-dev/neofs-node'
        version: 'v0.50.2'
        file: 'neofs-cli-{{ arch }}'

    neofs_adm:
        repo: 'nspcc-dev/neofs-node'
        version: 'v0.50.2'
        file: 'neofs-adm-{{ arch }}'

    neofs_ir:
        repo: 'nspcc-dev/neofs-node'
        version: 'v0.50.2'
        file: 'neofs-ir-{{ arch }}'

    neofs_lens:
        repo: 'nspcc-dev/neofs-node'
        version: 'v0.50.2'
        file: 'neofs-lens-{{ arch }}'

    neofs_node:
        repo: 'nspcc-dev/neofs-node'
        version: 'v0.50.2'
        file: 'neofs-node-{{ arch }}'

    neofs_s3_gw:
        repo: 'nspcc-dev/neofs-s3-gw'
        version: 'v0.41.5'
        file: 'neofs-s3-gw-{{ arch }}'

    neofs_s3_authmate:
        repo: 'nspcc-dev/neofs-s3-gw'
        version: 'v0.41.5'
        file: 'neofs-s3-authmate-{{ arch }}'

    neofs_rest_gw:
        repo: 'nspcc-dev/neofs-rest-gw'
        version: 'v0.15.1'
        file: 'neofs-rest-gw-{{ arch }}'

    neo_go:
        repo: 'nspcc-dev/neo-go'
        version: 'v0.114.0'
        file: 'neo-go-{{ arch }}'

    neofs_contract:
        repo: 'nspcc-dev/neofs-contract'
        version: 'v0.25.1'
        file: 'neofs-contract-v0.25.1.tar.gz'

    warp:
        repo: 'minio/warp'
        version: 'v1.0.2'
        file: '{{ warp_binary_name }}'

    awscli:
        version: '2.22.35'
